name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "modules/**"
      - "project/**"
      - ".scalafmt.conf"
      - ".github/**"
      - "build.sbt"
      - "git-hook.sbt"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  scalafmt:
    if: ${{(github.event_name == 'pull_request' && !contains(github.event.pull_request.body, '[skip ci]'))}}
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./bin/scalafmt --test
  cross-compilation:
    if: ${{(github.event_name == 'pull_request' && !contains(github.event.pull_request.body, '[skip ci]'))}}
    name: Cross Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: coursier/setup-action@v1.3.5
        with:
          apps: sbt
      - run: sbt +Test/compile
  test:
    if: ${{(github.event_name == 'pull_request' && !contains(github.event.pull_request.body, '[skip ci]'))}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            jvm: 'adoptium:1.8.0-372'
          - os: windows-latest
            jvm: 'adoptium:1.11.0.19'
          - os: macOS-latest
            jvm: 'adoptium:1.17.0.7'
          - os: ubuntu-latest
            jvm: 'adoptium:1.20.0.1'
    name: Unit Tests on ${{ matrix.os }} -- ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: coursier/setup-action@v1.3.5
      with:
        jvm: ${{ matrix.jvm }}
        apps: sbt
    - name: Unit tests
      run: sbt test
      shell: bash
  scripted-test:
    if: ${{(github.event_name == 'pull_request' && !contains(github.event.pull_request.body, '[skip ci]'))}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            jvm: 'adoptium:1.8.0-372'
          - os: ubuntu-latest
            jvm: 'adoptium:1.11.0.19'
          - os: macOS-latest
            jvm: 'adoptium:1.17.0.7'
    name: Scripted Tests on ${{ matrix.os }} -- ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: coursier/setup-action@v1.3.5
      with:
        jvm: ${{ matrix.jvm }}
        apps: sbt
    - name: Scripted tests
      run: sbt sbtPlugin/scripted
      shell: bash
